server:
  port: 8888
student:
  name: qihuis
  age: 18
#content: "name:${name},age:${age}"
remote:
  userName: qihuis
  password: 11111111
  baseUrl: https://135.252.247.61:8443
spring:
  profiles:
    include: new
#如果要通过jar包启动并引用外部配置文件可以使用
#java -jar demo.jar --spring.config.location=application.yml